# GitHub Pages Configuration for UP Language Specification

# Theme - Clean, minimal, grayscale design
theme: jekyll-theme-minimal

# Site settings
title: "UP (Unified Properties)"
description: "A Human-Friendly Data Serialization Format"
url: "https://uplang.org"
baseurl: ""

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

# Plugins
plugins:
  - jekyll-relative-links
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-titles-from-headings
  - jekyll-github-metadata

# Relative links
relative_links:
  enabled: true
  collections: true

# Optional front matter
optional_front_matter:
  remove_originals: true

# Titles from headings
titles_from_headings:
  enabled: true
  strip_title: true
  collections: true

# Exclude from build
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .bundle
  - .git
  - .github
  - Makefile
  - "*.sh"

# Include
include:
  - _config.yml
  - CONTRIBUTING.md
  - SYNTAX-REFERENCE.md
  - TEMPLATING.md
  - SCHEMA-VALIDATION.md
  - DYNAMIC-NAMESPACES.md
  - IMPLEMENTATIONS.md

# Collections
collections:
  examples:
    output: true
    permalink: /examples/:name

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: "default"

